### ISSUE TITLE
VCF alternative sequence padding

### ISSUE THREAD

**Issue by zeeev** [nh13/DWGSIM#12]
Greetings,

I’m simulating 100bp, 500bp, 2k, 10kb using DWGSIM and a reference sequence that is 11Mb long.  I’m having some trouble with the VCF files produced.  It  SEEMs like there is some strange padding going on with the position and sequence provided.  For example at position 5,411 there is a 10kb deletion, but the position and the sequence do not match.

I have highlighted where the deletion starts (*T*).  What is the sequence 5’ of the breakpoint of the deletion?  Across the different INDEL sizes the padding doesn’t seem consistent.

help?

5’

TTGTTTTGAAAACTTTTTTCTCTATCACAGTCTCTTAGTTATTGTTTGTTTTTTTCCCAAATATGTAATCATTCTGGTTTTCATCACGGAGCTTGCAGATGGGGAGTAAGAAGCTATTTGATTGCTTGCTCTG*T*ATTTTGTAATAGTGTCAAACATAACTTTTTCCAAAAGGTCTCCTTAAAGGAAACGGTGGCTCTGAATTTACAATGTTTTGAATTGAGGGCGCTGGGGGGTGGAATCTACTGAATCAATGAGGTTACACTTGCCTAAGCAAAATCTAAATTGGGCCTCTTGGCTGTAGAAAAGTAAAAGGGACAGAGAATAGAAAAATGCATGGCAAGGAAGGGATCCTGCATTTTGAAGTTAGTGGCTGTTAAGCCTCACACCTCAGCTTTTCCTGCCTGATTGCTATTCTTTCCCAGGTTCAAAGAACACTGAGCTAAGAGACCAGATTTGGAATAAGGGCTGCATCAGCGATCAGAGTTCTTCCCTGAAGAAGAACCTTCATGGAATGCATTATTCTGTGTTTAAGATATTCTGTTTGGCAAAGAATTTTGCACGTTTGTGGGAAGCAATGTGAGAAATGCAACTGGTAAATCCCTGAAGCTCTTATTTTTGCATATGAATAAGTACCTCAGGATGGCAACTGTTCA….

3'

**Comment by nh13** [comment]
@zeeev I realize this is more than a year and a half old, so if you want me to take a look, please open up another issue.  My apologies for not seeing this sooner.
