### ISSUE TITLE
Typing errors in dwgsim_eval output

### ISSUE THREAD

**Issue by karel-brinda** [nh13/DWGSIM#13]
There are some mistakes in the description generated by dwgsim_eval:
* "*that should be unmapped be mapped*" appears on several places
*  "*# mc' + mi' + mu' + um' + uu' | the total number of reads mapped at the threshold\n*" should be probably replaced by "*# mc + mi + mu + um + uu | the total number of reads mapped at the threshold\n*"

**Comment by nh13** [comment]
Fixed in #14
