### ISSUE TITLE
Perl executables

### ISSUE THREAD

**Issue by jerowe** [nh13/DWGSIM#16]
Perl executables are

#!/bin/perl and #!/usr/bin/perl.

It would be much nicer if they were

#!/usr/bin/env perl

**Comment by nh13** [comment]
I agree, are you able to make a pull request and I will merge it in?

**Comment by jerowe** [comment]
Sure.

**Comment by nh13** [comment]
Fixed: https://github.com/nh13/DWGSIM/pull/17
