### ISSUE TITLE
Conflict between input and output for option "mutations txt file to re-create"

### ISSUE THREAD

**Issue by namsyvo** [nh13/DWGSIM#18]
Hi all,

I'm using DWGSIM to simulate reads with my own mutations set. The problem is DWGSIM produces the output mutations set (in text file) which is different from my own mutations set. Could you check it for me?

I attach here the mutation files I used. The reference genome I used is NCBI GRCh37 p.13, Chromosome 1 (it is too big so I do not attach here, I hope you have it, if not, please let me know). The commands I used to generate simulated reads are as follows (I tried both):
[my.mutations.txt](https://github.com/nh13/DWGSIM/files/93668/my.mutations.txt)

dwgsim -N 100000 -1 100 -2 100 -e 0.00015-0.0015 -E 0.00015-0.0015 -m my.mutations.txt GRCh37_chr1.fasta  dwgsim_reads

dwgsim -N 100000 -1 100 -2 100 -e 0.00015-0.0015 -E 0.00015-0.0015 -r 0 -m my.mutations.txt GRCh37_chr1.fasta  dwgsim_reads

Thanks.

**Comment by nh13** [comment]
I think it may have something to do with justifying deletions in my own investigation. Could you post a diff of the two `my.mutations.txt` files?

**Comment by namsyvo** [comment]
Thank you for your quick reply. I attach here the input (my.mutations.txt) and output (dwgsim_reads.mutations.txt) from my above running. The diff_mut.txt is generated from diff command on Linux. There are many different locations, the first one is location 819121 in my input file and location 819120 in DWGSIM's output file. Could you check it? Thanks.
[my.mutations.txt](https://github.com/nh13/DWGSIM/files/93758/my.mutations.txt)
[dwgsim_reads.mutations.txt](https://github.com/nh13/DWGSIM/files/93759/dwgsim_reads.mutations.txt)
[diff_mut.txt](https://github.com/nh13/DWGSIM/files/93760/diff_mut.txt)

**Comment by nh13** [comment]
Thanks, it's going to take a while to debug this, both in length and when I can start, so please be patient.  As I am not funded to support this, I have to prioritize my funded work.  Please do know that I am aware.

**Comment by namsyvo** [comment]
You're welcome. Please let me know if you need more information. Hope to hear from you soon. Thank you.

**Comment by nh13** [comment]
@namsyvo I think this is a combination of two things.  The first is there is an outstanding bug that reports an insertion position off-by-one (see #22).  The second is that insertions and deletions are "left-justified" prior to being simulated, and the output mutations file has those "left-justified" mutations (a good example can be seen here: http://genome.sph.umich.edu/wiki/Variant_Normalization#Left_alignment). 

Please try the branch on #22 and let me know if there are any issues.
