### ISSUE TITLE
error generating insertion

### ISSUE THREAD

**Issue by Esbertrand** [nh13/DWGSIM#19]
Hello,

i'm trying to generate fatsq files with dwgsim  using a mutation txt file.
It worked perfecty with dwgsim 1.10 but not anymore with the 1.11.
Several indels in my file lead to  src/dwgsim.c:760: dwgsim_core: Assertion `0 <= byte_index' failed.
 or  280000dwgsim: src/dwgsim.c:741: dwgsim_core: Assertion `0 <= byte_index' failed.

Here an example of insertion :  1	15439084	-	AGGTCTTTTTTTTCTTCTCCCAGCGGC	2

My command : dwgsim -e 0.001-0.01 -E 0.001-0.01  -C ${COVERAGE} -1 100 -2 100 -y 0 -c 0 -r 0 -R 0  -x ${bed}  -m ${PROJECTDIR}/test3.txt  ${PATHTOREF}   ${PROJECTDIR}/'read_simulation_'${Toss}

I attached test3.txt file to this message and the problematic insertion is the last mutation of the file. 

Any idea?

Thanks in advance.

Bertrand
[test3.txt](https://github.com/nh13/DWGSIM/files/127877/test3.txt)

**Comment by Esbertrand** [comment]
sorry i attached the file without the problematic mutation, this one is the good one
[test3.txt](https://github.com/nh13/DWGSIM/files/128050/test3.txt)

**Comment by nh13** [comment]
I'll need to know a coverage value (`${COVERAGE}`) and the reference sequence (`${PATHTOREF}) that you are using.  Thanks for posting the bug report!

**Comment by Esbertrand** [comment]
coverage 40 and ref human_g1k_v37.fasta

**Comment by nh13** [comment]
@Esbertrand my apologies for the delay, but you wouldn't have the `${bed}` file still would you?

**Comment by nh13** [comment]
@Esbertrand Looks like I was able to reproduce and I have a pull request.  Thanks for reporting!

**Comment by Esbertrand** [comment]
Hi,

the bed file is attached.
[test.txt](https://github.com/nh13/DWGSIM/files/368830/test.txt)

**Comment by nh13** [comment]
@Esbertrand I have a fix (see #24).  I am going to merge it in.  Let me know if there are any issues.
