### ISSUE TITLE
strand information in read ids?

### ISSUE THREAD

**Issue by lonestar21** [nh13/DWGSIM#20]
Hi.
I know dwgsim isn't writting to simulate strand-specific RNAseq data.   However, I thought I'd use it for a similar application where I only want reads from one strand.

Is it correct that we should have equal numbers of reads (within tolerance) from each of the strands?   

I thought that I could figure out the strand of the simulated fragment by looking at the read ids where this id:
@fastq-id_618_571_1_0_0_0_0:0:0_0:0:0_7/1
would be on the positive strand because the digit after "571" is a 1.    However, I've since started to doubt this understanding because in my 10 million read fragments about 7 million have a 1 in that location.

Is there a way to get the strand of the simulated fragment from the read name?

**Comment by nh13** [comment]
See if this helps: https://github.com/nh13/DWGSIM/wiki/Simulating-Reads-with-DWGSIM

**Comment by lonestar21** [comment]
Bingo.
Missed that section when I read through earlier.
thanks,
RIchard


On 04/07/2016 11:25 AM, Nils Homer wrote:
>
> See if this helps: 
> https://github.com/nh13/DWGSIM/wiki/Simulating-Reads-with-DWGSIM
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nh13/DWGSIM/issues/20#issuecomment-207037623>
>

-- 
The contents of this electronic mail transmission are intended to be CONFIDENTIAL and for the sole use of the designated recipient. If this message has been misdirected, please contact the sender as soon as possible.

**Comment by nh13** [comment]
No problem, I am glad you are using it.
