### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by ashleymaeconard** [nh13/DWGSIM#27]
The website https://sourceforge.net/apps/mediawiki/dnaa/index.php?title=Whole_Genome_Simulation does not work. It says page not found.

**Comment by nh13** [comment]
@ashleymaeconard it don't think I have maintained dwgsim on sourceforge for a long time.  Take a look at the wiki here: https://github.com/nh13/DWGSIM/wiki

Where did you find the above link?

**Comment by ashleymaeconard** [comment]
I found it in your README, github, and on davetang's blog, as well as in biostars

**Comment by nh13** [comment]
Thanks for posting back! I updated the README: https://github.com/nh13/DWGSIM/pull/29
Unfortunately I am not able to forward the other links.
