### ISSUE TITLE
lzma.h error

### ISSUE THREAD

**Issue by ashleymaeconard** [nh13/DWGSIM#28]
When I download and try installing dwgsim I get the following error. Here are my commands:
-----------------
$ git clone https://github.com/nh13/DWGSIM.git
Download SAMTools from http://sourceforge.net/projects/samtools/files/samtools/ and place into the same directory as DWGSIM
$ cd DWGSIM
$ tar -xjf samtools-0.1.18.tar.bz2
$ mv samtools-0.1.18 samtools
$ make 
-----------------
ERROR:
cram/cram_io.c:60:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^
1 error generated.
make[2]: *** [cram/cram_io.o] Error 1
make[1]: *** [htslib-1.4/libhts.a] Error 2
make: *** [all-recur] Error 1

What should I do? It is not working to type "dwgsim".

**Comment by nh13** [comment]
The short [readme](https://github.com/nh13/DWGSIM/blob/master/README) on the [splash page](https://github.com/nh13/DWGSIM) says to do the following:
```
git clone --recursive https://github.com/nh13/DWGSIM.git
```

**Comment by ashleymaeconard** [comment]
Hello again, 
I apologize for that. Indeed it does! I wanted to ask, I have been getting this error. What needs to change about my command line?
./dwgsim -n 101 -z -1 -e 0.01 -d 1 -r 0 -1 101 -2 0 ../hg38.fa dwgsim.out

I get this error:
Error: command line option -n is not a number [-1]
