### ISSUE TITLE
make: *** [all-recur] Error 1 when installing DWGSIM

### ISSUE THREAD

**Issue by phoebee-h** [nh13/DWGSIM#31]
Hello everyone, and hello to Nils,
My name is Phoebe.
Everything seemed to work fine until I got this information. I had the complete package including samtools in its subdirectory. I have no idea what is going on. 

make[1]: Leaving directory `/home/phoebe/DWGSIM/samtools'
make[1]: Entering directory `/home/phoebe/DWGSIM'
make[2]: Entering directory `/home/phoebe/DWGSIM/samtools'
make[2]: Nothing to be done for `lib'.
make[2]: Leaving directory `/home/phoebe/DWGSIM/samtools'
make[2]: Entering directory `/home/phoebe/DWGSIM'
make[2]: Nothing to be done for `lib'.
make[2]: Leaving directory `/home/phoebe/DWGSIM'
gcc -c -g -Wall -O3  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -DPACKAGE_VERSION=\"0.1.11\" -I. src/dwgsim.c -o src/dwgsim.o
src/dwgsim.c: In function ‘dwgsim_core’:
src/dwgsim.c:868: error: ‘unsignedf’ undeclared (first use in this function)
src/dwgsim.c:868: error: (Each undeclared identifier is reported only once
src/dwgsim.c:868: error: for each function it appears in.)
src/dwgsim.c:868: error: expected ‘)’ before ‘long’
src/dwgsim.c:868: error: expected ‘)’ before ‘ii’
src/dwgsim.c:902: error: expected ‘)’ before ‘long’
src/dwgsim.c:902: error: expected ‘)’ before ‘ii’
make[1]: *** [src/dwgsim.o] Error 1
make[1]: Leaving directory `/home/phoebe/DWGSIM'
make: *** [all-recur] Error 1

Thank you.

**Comment by nh13** [comment]
Can you print look at line `868` in your source code and print that here?  I have neither heard of a `unsignedf` (the `f` before), nor does google reveal anything.

**Comment by phoebee-h** [comment]
Here is the original code in src/dwgsim.c, line 868 and 902, respectively:
(unsignedf long long)ii, j+1);
(unsignedf long long)ii);

As you mentioned, I then deleted the "f", making the source code like this:
(unsigned long long)ii, j+1);
(unsigned long long)ii);
Then, no such an error message I've got.
But, still some problems showed up as below:

make[1]: Leaving directory `/home/phoebe/DWGSIM/samtools'
make[1]: Entering directory `/home/phoebe/DWGSIM'
make[2]: Entering directory `/home/phoebe/DWGSIM/samtools'
make[2]: Nothing to be done for `lib'.
make[2]: Leaving directory `/home/phoebe/DWGSIM/samtools'
make[2]: Entering directory `/home/phoebe/DWGSIM'
make[2]: Nothing to be done for `lib'.
make[2]: Leaving directory `/home/phoebe/DWGSIM'
gcc -c -g -Wall -O3  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -DPACKAGE_VERSION=\"0.1.11\" -I. src/dwgsim.c -o src/dwgsim.o
gcc -g -Wall -O3  -o dwgsim src/dwgsim_opt.o src/mut.o src/contigs.o src/regions_bed.o src/mut_txt.o src/mut_bed.o src/mut_vcf.o src/mut_input.o src/dwgsim                                                                                                                                                                  .o -lm -lz -lpthread
gcc -c -g -Wall -O3  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -DPACKAGE_VERSION=\"0.1.11\" -I. src/dwgsim_eval.c -o src/dwgsim_eval.o
make[1]: *** No rule to make target `samtools/knetfile.o', needed by `dwgsim_eval'.  Stop.
make[1]: Leaving directory `/home/phoebe/DWGSIM'
make: *** [all-recur] Error 1

**Comment by kma** [comment]
Hi,

try make clean && make

Best

**Comment by phoebee-h** [comment]
Thank you kma,
But it still doesn't work. I'll keep figuring this out.
Thanks again!

**Comment by phoebee-h** [comment]
Hi, 
Not sure if it's the problem of samtools' version. I can finally make it work.

I've already had samtools 1.3.1 installed in another directory. I've made symbolic link but it did not work, which showed the same result as in SEQanswers (gprakhar has asked before).  http://seqanswers.com/forums/showthread.php?t=22578
Also, renaming the directory to "samtools" is necessary so I did that. Still not working.

Finally, I downloaded the "samtools @ 28391e5" that Nils provided and put it under the directory of DWGSIM with renaming. It finally works!

Though it might sound stupid for doing all this, I'm new in the bioinformatics field.
Just hope others encountering the similar problems can benefit.
Thanks!

**Comment by nh13** [comment]
@phoebee-h the version of samtools we use has not been updated in a while, and I am loathe to do it as the new stuff isn't really needed.  I believe `git clone --recursive` should clone both dwgsim as well as samtools.  Thanks for posting back!
