### ISSUE TITLE
-n is not a number

### ISSUE THREAD

**Issue by ashleymaeconard** [nh13/DWGSIM#32]
Hello, I have been getting this error. What needs to change about my command line? ./dwgsim -n 101 -z -1 -e 0.01 -d 1 -r 0 -1 101 -2 0 ../hg38.fa dwgsim.out

I get this error:
Error: command line option -n is not a number [-1]

I have been reading the Options, and to my understanding it should work. -n followed by integers denote the maximum number of Ns allowed in a given read.

Thank you in advance!

**Comment by nh13** [comment]
Thanks for the bug report, omitting `-z` should work, but I have also fixed the bug.

**Comment by ashleymaeconard** [comment]
Hello, I re-cloned the repo but now I get this error. These are my commands:
$git clone --recursive https://github.com/nh13/DWGSIM.git
$cd DWGSIM
$make

Error is:
...
src/dwgsim.c: In function 'dwgsim_core':
src/dwgsim.c:868:36: error: 'unsignedf' undeclared (first use in this function)
                                   (unsignedf long long)ii, j+1);
                                    ^
src/dwgsim.c:868:36: note: each undeclared identifier is reported only once for each function it appears in
src/dwgsim.c:868:46: error: expected ')' before 'long'
                                   (unsignedf long long)ii, j+1);
                                              ^
src/dwgsim.c:868:56: error: expected ')' before 'ii'
                                   (unsignedf long long)ii, j+1);
                                                        ^
src/dwgsim.c:902:42: error: expected ')' before 'long'
                               (unsignedf long long)ii);
                                          ^
src/dwgsim.c:902:52: error: expected ')' before 'ii'
                               (unsignedf long long)ii);
                                                    ^
Makefile:22: recipe for target 'src/dwgsim.o' failed
make[1]: *** [src/dwgsim.o] Error 1
make[1]: Leaving directory '/gpfs/main/research/compbio/software/DWGSIM/DWGSIM'
Makefile:25: recipe for target 'all-recur' failed
make: *** [all-recur] Error 1

**Comment by ashleymaeconard** [comment]
Also, by removing the random seed (-z), what is the default? I would like to be able to reproduce my results at a later time if needed. 
Further, here is my new command and error:

./dwgsim -n 101 -e 0.01 -d 1 -r 0 -1 101 -2 0 ../hg38.fa dwgsim.out
[main] fail to open file '../hg38.fa'. Abort!
Aborted
 
What should I do in this case?
