### ISSUE TITLE
Error when cloning repo and removing -r command

### ISSUE THREAD

**Issue by ashleymaeconard** [nh13/DWGSIM#34]
Hello, I have two questions:

1) I re-cloned the repo but now I get this error. 
These are my commands:
 $git clone --recursive https://github.com/nh13/DWGSIM.git
 $cd DWGSIM 
$make

Error is:
...
gcc -c -g -Wall -O3  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -DPACKAGE_VERSION=\"0.1.11\" -I. src/dwgsim.c -o src/dwgsim.o
src/dwgsim.c: In function 'dwgsim_core':
src/dwgsim.c:868:36: error: 'unsignedf' undeclared (first use in this function)
                                   (unsignedf long long)ii, j+1);
                                    ^
src/dwgsim.c:868:36: note: each undeclared identifier is reported only once for each function it appears in
src/dwgsim.c:868:46: error: expected ')' before 'long'
                                   (unsignedf long long)ii, j+1);
                                              ^
src/dwgsim.c:868:56: error: expected ')' before 'ii'
                                   (unsignedf long long)ii, j+1);
                                                        ^
src/dwgsim.c:902:42: error: expected ')' before 'long'
                               (unsignedf long long)ii);
                                          ^
src/dwgsim.c:902:52: error: expected ')' before 'ii'
                               (unsignedf long long)ii);
                                                    ^
Makefile:22: recipe for target 'src/dwgsim.o' failed
make[1]: *** [src/dwgsim.o] Error 1
make[1]: Leaving directory '/gpfs/main/research/compbio/software/DWGSIM/DWGSIM'
Makefile:25: recipe for target 'all-recur' failed
make: *** [all-recur] Error 1

2) Also, by removing the random seed (-z), what is the default? I would like to be able to reproduce my results at a later time if needed. Further, here is my new command and error:

$ ./dwgsim -n 101 -e 0.01 -d 1 -r 0 -1 101 -2 0 ../hg38.fa dwgsim.out
 [main] fail to open file '../hg38.fa'. Abort! 
Aborted

What should I do in this case?

**Comment by ashleymaeconard** [comment]
Is there a small tutorial you can show me of a instance which works? That way I can try to find a work around in the meantime?

**Comment by nh13** [comment]
It looks like the path to the FASTA file is invalid.

**Comment by ashleymaeconard** [comment]
Hello, 
1) In regards to number 2. Can I use -z? Was this an error and if so, was it fixed?
2) For the Aborted process, I found out that the hg38 file had been corrupted. 
3) Thank you for fixing question 1.

Thank you for your help!

**Comment by nh13** [comment]
@ashleymaeconard 
1. fixed here: https://github.com/nh13/DWGSIM/pull/33.  You'll need to update your local copy to get hthe fix.
2. Excellent!
3. Np
