### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by brittneykeel** [nh13/DWGSIM#35]
When attempting to run the "make" command is receive the error shown below. Any suggestions?

~/DWGSIM$ make
make[1]: Entering directory '/Jake/home/brittney.keel/DWGSIM/samtools'
make[2]: Entering directory '/Jake/home/brittney.keel/DWGSIM/samtools'
make[2]: Nothing to be done for 'lib'.
make[2]: Leaving directory '/Jake/home/brittney.keel/DWGSIM/samtools'
make[2]: Entering directory '/Jake/home/brittney.keel/DWGSIM/samtools/bcftools'
make[2]: Nothing to be done for 'lib'.
make[2]: Leaving directory '/Jake/home/brittney.keel/DWGSIM/samtools/bcftools'
make[2]: Entering directory '/Jake/home/brittney.keel/DWGSIM/samtools/misc'
make[2]: Nothing to be done for 'lib'.
make[2]: Leaving directory '/Jake/home/brittney.keel/DWGSIM/samtools/misc'
gcc -g -Wall -O3  -o samtools bam_tview.o bam_plcmd.o sam_view.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o kaln.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o bam_tview_curses.o bam_tview_html.o  libbam.a -Lbcftools -lbcf  -lcurses  -lm -lz -lpthread
make[1]: Leaving directory '/Jake/home/brittney.keel/DWGSIM/samtools'
make[1]: Entering directory '/Jake/home/brittney.keel/DWGSIM'
make[2]: Entering directory '/Jake/home/brittney.keel/DWGSIM/samtools'
make[2]: Nothing to be done for 'lib'.
make[2]: Leaving directory '/Jake/home/brittney.keel/DWGSIM/samtools'
make[2]: Entering directory '/Jake/home/brittney.keel/DWGSIM'
make[2]: Nothing to be done for 'lib'.
make[2]: Leaving directory '/Jake/home/brittney.keel/DWGSIM'
gcc -c -g -Wall -O3  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -DPACKAGE_VERSION=\"0.1.11\" -I. src/dwgsim.c -o src/dwgsim.o
src/dwgsim.c: In function 'dwgsim_core':
src/dwgsim.c:868:36: error: 'unsignedf' undeclared (first use in this function)
                                   (unsignedf long long)ii, j+1);
                                    ^
src/dwgsim.c:868:36: note: each undeclared identifier is reported only once for each function it appears in
src/dwgsim.c:868:46: error: expected ')' before 'long'
                                   (unsignedf long long)ii, j+1);
                                              ^
src/dwgsim.c:868:56: error: expected ')' before 'ii'
                                   (unsignedf long long)ii, j+1);
                                                        ^
src/dwgsim.c:902:42: error: expected ')' before 'long'
                               (unsignedf long long)ii);
                                          ^
src/dwgsim.c:902:52: error: expected ')' before 'ii'
                               (unsignedf long long)ii);
                                                    ^
In file included from src/dwgsim.c:45:0:
src/dwgsim.c: At top level:
src/mut.h:62:1: warning: inline function 'mut_get_ins_long_n' declared but never defined
 mut_get_ins_long_n(uint8_t *ins, uint32_t *n);
 ^
src/mut.h:59:1: warning: inline function 'mut_get_ins_bytes' declared but never defined
 mut_get_ins_bytes(int32_t n);
 ^
Makefile:22: recipe for target 'src/dwgsim.o' failed
make[1]: *** [src/dwgsim.o] Error 1
make[1]: Leaving directory '/Jake/home/brittney.keel/DWGSIM'
Makefile:25: recipe for target 'all-recur' failed
make: *** [all-recur] Error 1

**Comment by nh13** [comment]
Can you tell me what operating system, which version of gcc (`gcc --version`), and which version of `dwgsim` you are using (hopefully the latest from the master branch).

**Comment by nh13** [comment]
Fixed in #36.  Thank-you for the report!

**Comment by brittneykeel** [comment]
Hi Nils,

I actually figured out the issue a moment ago. It appears there is a typo in Lines 868 and 902 of dwgsim.c.

unsignedf --> unsigned

I fixed this in the code and it compiled with no problems!

-Brittney

**Comment by nh13** [comment]
Yup, that was the fix I merged, thanks!
