### ISSUE TITLE
Feature to disable the creation of each output file

### ISSUE THREAD

**Issue by niemasd** [nh13/DWGSIM#39]
I am trying to use DWGSIM to simulate multiple replicates of WGS Illumina reads at 30x coverage on hg19, which creates massively large files. However, for my purposes, I don't care about the `.bfast.fastq` files (I only care about `.bwa.read1.fastq` and `.bwa.read2.fastq`), but because DWGSIM creates all of the files, I end up wasting space and cannot run as many in parallel because I need to wait for the running ones to finish, then delete everything I don't need and gzip `.bwa.read1.fastq` and `.bwa.read2.fastq`, then kick off more.

It would be a nice feature to be able to disable creating each of the output files so that I would be able to disable everything except for the `.bwa.read1.fastq` and `.bwa.read2.fastq` files that I want, which would more than halve the space taken by the output

**Comment by nh13** [comment]
Sounds like a useful feature.  Unfortunately I don't have a timetable for when I would look at implementing it (this is all Pro Bono), but I will keep it here in case I have spare time.  I always welcome pull requests.

**Comment by nh13** [comment]
@niemasd easier than I thought!

**Comment by niemasd** [comment]
Excellent, thanks so much for the quick implementation!
