### ISSUE TITLE
Feature to create gzipped output files instead of plaintext

### ISSUE THREAD

**Issue by niemasd** [nh13/DWGSIM#40]
I am trying to use DWGSIM to simulate multiple replicates of WGS Illumina reads at 30x coverage on hg19, which creates massively large files. Because the output files are not gzipped, I end up wasting space and cannot run as many in parallel because I need to wait for the running ones to finish, then delete everything I don't need and gzip `.bwa.read1.fastq` and `.bwa.read2.fastq`, then kick off more.

It would be a nice feature to be able to create gzipped output files instead of plaintext to save a ton of space, especially given that most people work with gzipped FASTQ files anyways

**Comment by nh13** [comment]
I am making the FASTQs output in gzip format by default as I don't see any harm in that.

**Comment by niemasd** [comment]
Wow, you're awesome! Thanks so much for getting to these so quickly! And great work with the tool!
