### ISSUE TITLE
How to mark Quailty Score?

### ISSUE THREAD

**Issue by studB** [nh13/DWGSIM#46]
Hello 

I'm using dwgism to transform file,fa into file.fastq.

As you know, file.fa is a file that has only text line like AGCCAGATCCGG...
Then, I put this file into dwgsim and, got file.fastq that have QC.

I wonder how dwgsim mark the QC on the file.fa.
There is not reference data option in dwgsim.

What criteria do dwgism use for this process?
Just, statistical inference?

I'm very very confusing.

Thank you

bdy6290@naver.com

**Comment by nh13** [comment]
Take a look at the wikipedia entry for FASTQ.  You'll also need to be familiar with actual NGS data, where FASTA for the reference and FASTQ for the reads are ubiquitous, so is a reasonable requirement for using dwgsim.  Unfortunately, I am not paid to support dwgsim and so I will not have time to bring you up to speed.  I would ask a mentor or teacher for help understanding the basics before starting on dwgsim.
