### ISSUE TITLE
The read name explanation is not clear

### ISSUE THREAD

**Issue by bbsunchen** [nh13/DWGSIM#49]
In the wiki, https://github.com/nh13/DWGSIM/wiki/Simulating-Reads-with-DWGSIM#Read_names_explained

For read name `@<#1>_<#2>_<#3>_<#4>_<#5>_<#6>_<#7>_<#8>:<#9>:<#10>_<#11>:<#12>:<#13>_<#14>`

```
2. start end 1 (one-based)
3. start end 2 (one-based)
```

I do not quite understand what does "start end" means, is it the start position or the end position?

**Comment by nh13** [comment]
sorry, that's not clear.  It means for a paired end rate, the "start end 1" is the start position of the read for the first end/mate.  I have updated the wiki, and thanks for the report.
