### ISSUE TITLE
No Ns into simulates reads

### ISSUE THREAD

**Issue by jfourquet2** [nh13/DWGSIM#59]
Hi,
I am testing DWGSIM in order to simulate Illumina paired-end reads 2*150bp.
I have tested it with different genome sequences and different options.
I tried to find why I haven't any Ns into my simulates reads even if I choose the option -n 100 :
```
 DWGSIM/dwgsim -1 150 -2 150 -N 100 -n 100 -H /work2/genphyse/NED_metaG/Mock/genome/39950.4.fna 39950.4_test_H_N100
[dwgsim_core] CP017037.1 length: 1274073
[dwgsim_core] 1 sequences, total length: 1274073
[dwgsim_core] Currently on: 
[dwgsim_core] 100
[dwgsim_core] Complete!
```
`grep N 39950.4_test_H_N100.bwa.read1.fastq` returns nothing.

Thanks a lot in advance for your answer !

**Comment by nh13** [comment]
@jfourquet2 the tool does not add in Ns into the reads itself, but instead it will ignore reads that have Ns when derived from the reference (which has the non-ACGT base).
