### ISSUE TITLE
Option -C

### ISSUE THREAD

**Issue by jfourquet2** [nh13/DWGSIM#60]
Hi,
I have investigated -C option and I don't well understand how does it mean.
I have simulated 2*150bp Illumina reads (with -H option) with a mean coverage of 100 for an example genome:
```
DWGSIM/dwgsim -C 100.00 -1 150 -2 150 -H /work2/genphyse/NED_metaG/Mock/genome/818.23.fna 818.23_C100.00 > 818.23_C100.00.out
[dwgsim_core] CP012937.1 length: 6487685
[dwgsim_core] 1 sequences, total length: 6487685
[dwgsim_core] Currently on: 
[dwgsim_core] 2276381
[dwgsim_core] Complete!
```
This genome length is 6487685 and if we want a coverage of 100 for each base, we want to simulate 6487685*100bp, soit 648768500bp. I simulate paired-end reads of 150bp, so I would have 648768500 /(150*2) = 2 162 562 reads. But I have 2276381 reads. How this number is obtained ?
Thanks a lot in advance for your answer !

**Comment by nh13** [comment]
I am on vacation for a week more so I’ll try to answer in a week or two thereafter. Thanks for your patience.

**Comment by nh13** [comment]
You can see the calculation here: https://github.com/nh13/DWGSIM/blob/bcb56ea846d398d7d4999eef41f4caa764247231/src/dwgsim.c#L591

You'd be right if we had no "random reads" introduced, but if 5% of the output reads are to be random (the default with `-y`), then we have to scale up the total # of reads to 5% more than `2,162,562`.  Note the genome may have multiple contigs, so the #s may be a bit off versus just using the genome length.
