### ISSUE TITLE
-e and -E option

### ISSUE THREAD

**Issue by jfourquet2** [nh13/DWGSIM#61]
Hi,
I have two questions about -e and -E options.
- which function is used when we use -e 0.01-0.1 and/or -E  0.01-0.1 ?
- On the header we can know how much sequencing errors the read contains (field 8 or 11 in your wiki) but we don't know how to see the position of the sequencing error in the read. Is there the possibility to have this position ?
Thanks a lot in advance !

**Comment by nh13** [comment]
@jfourquet2 

1. the error rate increases by a linear rate from the start (5' end) to the end.
2. I don't think we output this, but I'd be open to doing something to have this info, I just don't think I'll have time to do it as a community contribution (i.e. unpaid), so if you really want this feature, reach out.

**Comment by jfourquet2** [comment]
Thanks a lot for your answer @nh13 !
