### ISSUE TITLE
-i / -d / -s outer distance ?

### ISSUE THREAD

**Issue by jfourquet2** [nh13/DWGSIM#62]
Hi,
I have a question about the parameters -i, -d and -s.
Can you describe in details these options ?
I have read the wiki and there is a note about -d option "NB: the -d option was previously incorrectly stated as being the outer distance, but is in fact the inner distance. Thanks to Brent Pedersen! " but in the help of dwgsim it is noticed that we can use -i to use the inner distance and -d for the outer distance, so I don't understand this note...
Thanks a lot in advance !

**Comment by nh13** [comment]
* `-i` describes if the distance should be calculated as "inner" versus "outer"
* `-d` is the distance, who is dependent based on `-i`
* `-s` is the standard deviation for randomly picking an insert size based on a normal distribution with mean (`-d`) and standard deviation (`-s)

**Comment by nh13** [comment]
I updated the wiki too

**Comment by jfourquet2** [comment]
Thanks a lot @nh13 !
