### ISSUE TITLE
contig parsing in mut_txt.c required sorted input

### ISSUE THREAD

**Issue by fbattke** [nh13/DWGSIM#64]
There seems to be a bug in mutation txt parsing in mut_txt.c, line 53 ("i=0;"). This line should be INSIDE the while loop in line 54.., as otherwise parsing only works if contigs in the txt file are sorted identically to those in the fasta reference

**Comment by nh13** [comment]
@fbattke I think folks should have the same contig ordering as the FASTA, and so I have updated the error message in #66.  I don't see why the two should not be ordered the same (genomic coordinate order).  See other formats like VCF or SAM/BAM
