### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by as7a5** [nh13/DWGSIM#70]
Hi,
I have problem installing DWGSIM. the samtools and the correlated htslib dont download. My effort of manually download them leads to compilation time error. The cluster is running on RH 7.4 and I have tried gcc 6.1 and 4.8.

**Comment by nh13** [comment]
Can you try installing with bioconda: https://bioconda.github.io/recipes/dwgsim/README.html

**Comment by nh13** [comment]
0.1.13 is no bioconda
