### ISSUE TITLE
Contig not found error when using the -x option with multiple bed lines

### ISSUE THREAD

**Issue by gtollefson** [nh13/DWGSIM#72]
Hi,

I receive the following error when running dwgsim with the `-x`  option with a 5 region bed file. When I run the same command with a modified version of the bed file containing only 1 region line for each run, each run completed successfully. This looks like a bug with the `-x` functionality. 

Command:
`dwgsim -e 0.000 -E 0.000 -C 30 -1 150 -2 150 -r 0.00000 -F 0.000 -R 0.0 -x some_directory/5_sim_samples/regions_of_interest_5_samples.bed -q F some_directory/5_sim_samples/sample_1_mutations.fasta some_directory/5_sim_samples/sample_1_sim_reads
`

Error:
> Error: contig not found [chr17]

The bed file contents (tab delimited):
> chr3	179148523	179240093
> chr17	7668402	7687538
> chr16	68737225	68835548
> chr10	8058551	8058551
> chr2	178525989	178807423 
> chr7	55019101	55211628

Can you help me to troubleshoot?

Thank you,
George

**Comment by nh13** [comment]
What is the order of your contigs in your FASTA? The BED file should have entries in the same order.

**Comment by nh13** [comment]
Error message improved in #75
