### ISSUE TITLE
Generation of reads only on the first gene of a fasta file

### ISSUE THREAD

**Issue by SimoneRossi94** [nh13/DWGSIM#73]
Hi, 
Sorry to bother, but I can't make DWGSIM work on a fasta file that has four gene inside.
I'm generating a small number of reads (around 1000) and the mutation file shows SNP in all the genes. 
But when I open the fastq files I only have reads that have been generated on the first gene of the fasta file. 
Is there a way to fix this problem?

Thank you. 

P.S. this is the DWGSIM line 

dwgsim -N 880 -1 150 -2 150 -r 0.003 -e 0 -E 0 $work_dir/"gene_pipeline.fa" $output/forward.fastq $output/reverse.fastq

[forward.fastq.bwa.read2.fastq.gz](https://github.com/nh13/DWGSIM/files/9132262/forward.fastq.bwa.read2.fastq.gz)
[forward.fastq.bwa.read1.fastq.gz](https://github.com/nh13/DWGSIM/files/9132263/forward.fastq.bwa.read1.fastq.gz)
[gene_pipeline.fa.gz](https://github.com/nh13/DWGSIM/files/9132264/gene_pipeline.fa.gz)
[forward.fastq.mutations 2.txt](https://github.com/nh13/DWGSIM/files/9132309/forward.fastq.mutations.2.txt)

**Comment by nh13** [comment]
@SimoneRossi94 thank-you for including the input FASTA and your outputs.

(1) I think the `$output/reverse.fastq` isn't necessary and will be ignored.
(2) I ran the following without issue:

```
$ dwgsim -N 880 -1 150 -2 150 -r 0.003 -e 0 -E 0 gene_pipeline.fa output/output
$ grep ^@ output.bfast.fastq | cut -d '_' -f 1-4 | sort | uniq -c
 356 @bosTau9_all_mrna_BC103030
 576 @bosTau9_all_mrna_BC150136
 498 @bosTau9_all_mrna_BC151633
 238 @bosTau9_all_mrna_BT025443
  92 @rand_0_0_0
```

As you can see, I am getting decent coverage across contigs.  I do see that your FASTQs only have the first contig.

Can you tell me which version of dwgsim you're using (and if not the latest commit on github, can you try that)?

**Comment by SimoneRossi94** [comment]
Hi, 
I'm using DWGSIM 0.1.14.
I was able to solve the problem by modifying the command line as below:
dwgsim -C 20 -1 150 -2 150 -r 0.003 -e 0 -E 0 -R 0 -y 0 -n 0 $work_dir/gene_pipeline.fa $cartella_output/forward
Thank you for your help.
