### ISSUE TITLE
The coverage at the end of the sequence is close to 0

### ISSUE THREAD

**Issue by AlsoATraveler** [nh13/DWGSIM#81]
Hello, when I use dwgsim to simulate the sequence, I found that the coverage at the end of the sequence is close to 0, what is the reason for this?

Below is my command:
dwgsim -e 0 -E 0 -N 10 -C 1000 -1 100 -2 100 -r 0 -F 0 -R 0 -X 0 -y 0 -n 0 -c 0 -S 2 -n 2 -A 1 xxx_gene.fa result

**Comment by nh13** [comment]
See: https://github.com/nh13/DWGSIM/issues/71
